all: src/Packet.cpp src/sender.cpp src/receiver.cpp src/Ack.cpp
	#Building sendfile...
	g++ -pthread src/sender.cpp src/Packet.cpp src/CheckSum.cpp -o sendfile -std=c++11
	#Building recvfile...
	g++ src/receiver.cpp src/Ack.cpp src/CheckSum.cpp -o recvfile -std=c++11
